import os
from datetime import date, timedelta

from django.core.mail import send_mail

from ajenta_dashboard.celery import app
from .queries import calculate_concurrent_lines


@app.task
def send_email():
    username = 'All'
    start_date = end_date = date.today() - timedelta(1)

    ajenta_io_lines = calculate_concurrent_lines(username, 'ajenta_io', start_date, end_date)
    platformc_lines = calculate_concurrent_lines(username, 'platformc', start_date, end_date)

    subject = 'Maximum number of concurrent lines for ' + start_date.strftime("%d/%m/%Y")

    message = 'This is an automated email, generated by dashboard.ajenta.io\n\n' \
              'The maximum number of concurrent lines for ajenta.io on ' \
              + start_date.strftime("%d/%m/%Y") + ' was: ' + str(ajenta_io_lines[start_date]) + '.\n\n' \
              'The maximum number of concurrent lines for platformC on ' \
              + start_date.strftime("%d/%m/%Y") + ' was: ' + str(platformc_lines[start_date])

    send_mail(subject, message, os.environ['EMAIL_HOST_USER'], [os.environ['EMAIL_HOST_USER']], fail_silently=False)
