# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('callid', models.AutoField(db_column='CallID', primary_key=True, serialize=False)),
                ('uniquecallid', models.CharField(db_column='UniqueCallID', max_length=20)),
                ('conferencename', models.CharField(db_column='ConferenceName', max_length=200)),
                ('tenantname', models.CharField(db_column='TenantName', max_length=128)),
                ('conferencetype', models.CharField(db_column='ConferenceType', max_length=2)),
                ('endpointtype', models.CharField(db_column='EndpointType', max_length=1)),
                ('callerid', models.CharField(db_column='CallerID', max_length=200)),
                ('callername', models.CharField(blank=True, db_column='CallerName', max_length=200, null=True)),
                ('jointime', models.DateTimeField(db_column='JoinTime')),
                ('leavetime', models.DateTimeField(blank=True, db_column='LeaveTime', null=True)),
                ('callstate', models.CharField(db_column='CallState', max_length=80)),
                ('direction', models.CharField(db_column='Direction', max_length=1)),
                ('routerid', models.CharField(blank=True, db_column='RouterID', max_length=128, null=True)),
                ('gwid', models.CharField(blank=True, db_column='GWID', max_length=40, null=True)),
                ('gwprefix', models.CharField(blank=True, db_column='GWPrefix', max_length=20, null=True)),
                ('referencenumber', models.CharField(blank=True, db_column='ReferenceNumber', max_length=64, null=True)),
                ('applicationname', models.CharField(blank=True, db_column='ApplicationName', max_length=24, null=True)),
                ('applicationversion', models.CharField(blank=True, db_column='ApplicationVersion', max_length=32, null=True)),
                ('applicationos', models.CharField(blank=True, db_column='ApplicationOs', max_length=24, null=True)),
                ('devicemodel', models.CharField(blank=True, db_column='DeviceModel', max_length=50, null=True)),
                ('endpointpublicipaddress', models.CharField(db_column='EndpointPublicIPAddress', max_length=48)),
                ('callcompletioncode', models.CharField(db_column='CallCompletionCode', max_length=1)),
                ('extension', models.CharField(blank=True, db_column='Extension', max_length=64, null=True)),
                ('endpointguid', models.CharField(db_column='EndpointGUID', max_length=64)),
                ('accesstype', models.CharField(db_column='AccessType', max_length=1)),
                ('roomtype', models.CharField(db_column='RoomType', max_length=1)),
                ('roomowner', models.CharField(db_column='RoomOwner', max_length=40)),
            ],
            options={
                'db_table': 'ConferenceCall2',
                'managed': True,
            },
        ),
    ]
